<template>
    <section class="akn-chapter" id="chp_4" data-eid="chp_4"><h2>Chapter 4<br>Working equines</h2>
                                                                                                                                                  <section class="akn-section" id="sec_17" data-eid="sec_17"><h3>17. Permits to keep working equines</h3>
                                                                                                                                                    <section class="akn-subsection" id="sec_17__subsec_1" data-eid="sec_17__subsec_1"><span class="akn-num">(1)</span><span class="akn-content">
                                                                                                                                                        <span class="akn-blockList" id="sec_17__subsec_1__list_1" data-eid="sec_17__subsec_1__list_1">
                                                                                                                                                          <span class="akn-item" id="sec_17__subsec_1__list_1__item_a" data-eid="sec_17__subsec_1__list_1__item_a">
                                                                                                                                                            <span class="akn-num">(a)</span>
                                                                                                                                                            <span class="akn-p">Any <span class="akn-term term-link" data-refersto="#term-owner" id="sec_17__subsec_1__list_1__item_a__term_1" data-eid="sec_17__subsec_1__list_1__item_a__term_1" data-original-title="" title="">owner</span> who wants to put to work a <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_17__subsec_1__list_1__item_a__term_2" data-eid="sec_17__subsec_1__list_1__item_a__term_2" data-original-title="" title="">working equine</span>, must apply to the <span class="akn-term term-link" data-refersto="#term-Council" id="sec_17__subsec_1__list_1__item_a__term_3" data-eid="sec_17__subsec_1__list_1__item_a__term_3" data-original-title="" title="">Council</span> for a <span class="akn-term term-link" data-refersto="#term-permit" id="sec_17__subsec_1__list_1__item_a__term_4" data-eid="sec_17__subsec_1__list_1__item_a__term_4" data-original-title="" title="">permit</span>, in respect of such <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_17__subsec_1__list_1__item_a__term_5" data-eid="sec_17__subsec_1__list_1__item_a__term_5" data-original-title="" title="">working equine</span>.</span>
                                                                                                                                                          </span>
                                                                                                                                                          <span class="akn-item" id="sec_17__subsec_1__list_1__item_b" data-eid="sec_17__subsec_1__list_1__item_b">
                                                                                                                                                            <span class="akn-num">(b)</span>
                                                                                                                                                            <span class="akn-p">No more than one <span class="akn-term term-link" data-refersto="#term-permit" id="sec_17__subsec_1__list_1__item_b__term_1" data-eid="sec_17__subsec_1__list_1__item_b__term_1" data-original-title="" title="">permit</span> may be issued in respect of a <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_17__subsec_1__list_1__item_b__term_2" data-eid="sec_17__subsec_1__list_1__item_b__term_2" data-original-title="" title="">working equine</span>.</span>
                                                                                                                                                          </span>
                                                                                                                                                        </span>
                                                                                                                                                      </span></section><section class="akn-subsection" id="sec_17__subsec_2" data-eid="sec_17__subsec_2"><span class="akn-num">(2)</span><span class="akn-content">
                                                                                                                                                          <span class="akn-blockList" id="sec_17__subsec_2__list_1" data-eid="sec_17__subsec_2__list_1">
                                                                                                                                                            <span class="akn-listIntroduction">An application in terms of subsection (1) must be in writing on a prescribed form and must be accompanied by –</span>
                                                                                                                                                            <span class="akn-item" id="sec_17__subsec_2__list_1__item_a" data-eid="sec_17__subsec_2__list_1__item_a">
                                                                                                                                                              <span class="akn-num">(a)</span>
                                                                                                                                                              <span class="akn-p">the prescribed fee;</span>
                                                                                                                                                            </span>
                                                                                                                                                            <span class="akn-item" id="sec_17__subsec_2__list_1__item_b" data-eid="sec_17__subsec_2__list_1__item_b">
                                                                                                                                                              <span class="akn-num">(b)</span>
                                                                                                                                                              <span class="akn-p">documentary evidence that the <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_17__subsec_2__list_1__item_b__term_1" data-eid="sec_17__subsec_2__list_1__item_b__term_1" data-original-title="" title="">working equine</span> is suitable to pull a <span class="akn-term term-link" data-refersto="#term-animal_drawn_vehicle" id="sec_17__subsec_2__list_1__item_b__term_2" data-eid="sec_17__subsec_2__list_1__item_b__term_2" data-original-title="" title="">animal drawn vehicle</span>;</span>
                                                                                                                                                            </span>
                                                                                                                                                          </span>
                                                                                                                                                        </span></section><section class="akn-subsection" id="sec_17__subsec_3" data-eid="sec_17__subsec_3"><span class="akn-num">(3)</span><span class="akn-content">
                                                                                                                                                            <span class="akn-p">The <span class="akn-term term-link" data-refersto="#term-Council" id="sec_17__subsec_3__term_1" data-eid="sec_17__subsec_3__term_1" data-original-title="" title="">Council</span> may require the applicant to provide any further information which it considers relevant to enable it to make an informed decision.</span>
                                                                                                                                                          </span></section><section class="akn-subsection" id="sec_17__subsec_4" data-eid="sec_17__subsec_4"><span class="akn-num">(4)</span><span class="akn-content">
                                                                                                                                                              <span class="akn-p">The <span class="akn-term term-link" data-refersto="#term-Council" id="sec_17__subsec_4__term_1" data-eid="sec_17__subsec_4__term_1" data-original-title="" title="">Council</span> may refuse to consider an application in terms of subsection (1) in respect of which the provisions of subsection (2) have not been complied with or information contemplated in subsection (3), has not been furnished.</span>
                                                                                                                                                            </span></section><section class="akn-subsection" id="sec_17__subsec_5" data-eid="sec_17__subsec_5"><span class="akn-num">(5)</span><span class="akn-content">
                                                                                                                                                                <span class="akn-blockList" id="sec_17__subsec_5__list_1" data-eid="sec_17__subsec_5__list_1">
                                                                                                                                                                  <span class="akn-listIntroduction">The <span class="akn-term term-link" data-refersto="#term-Council" id="sec_17__subsec_5__list_1__term_1" data-eid="sec_17__subsec_5__list_1__term_1" data-original-title="" title="">Council</span> may only consider an application in terms of subsection (1) after receipt of a written report from an <span class="akn-term term-link" data-refersto="#term-authorised_official" id="sec_17__subsec_5__list_1__term_2" data-eid="sec_17__subsec_5__list_1__term_2" data-original-title="" title="">authorised official</span>-</span>
                                                                                                                                                                  <span class="akn-item" id="sec_17__subsec_5__list_1__item_a" data-eid="sec_17__subsec_5__list_1__item_a">
                                                                                                                                                                    <span class="akn-num">(a)</span>
                                                                                                                                                                    <span class="akn-p">as to whether the <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_17__subsec_5__list_1__item_a__term_1" data-eid="sec_17__subsec_5__list_1__item_a__term_1" data-original-title="" title="">working equine</span> for which the <span class="akn-term term-link" data-refersto="#term-permit" id="sec_17__subsec_5__list_1__item_a__term_2" data-eid="sec_17__subsec_5__list_1__item_a__term_2" data-original-title="" title="">permit</span> is required is likely to cause a nuisance in a <span class="akn-term term-link" data-refersto="#term-public_place" id="sec_17__subsec_5__list_1__item_a__term_3" data-eid="sec_17__subsec_5__list_1__item_a__term_3" data-original-title="" title="">public place</span> or its use may result in a contravention of section 19;</span>
                                                                                                                                                                  </span>
                                                                                                                                                                  <span class="akn-item" id="sec_17__subsec_5__list_1__item_b" data-eid="sec_17__subsec_5__list_1__item_b">
                                                                                                                                                                    <span class="akn-num">(b)</span>
                                                                                                                                                                    <span class="akn-p">setting out the results of an inspection of the <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_17__subsec_5__list_1__item_b__term_1" data-eid="sec_17__subsec_5__list_1__item_b__term_1" data-original-title="" title="">working equine</span> and its working circumstances; and</span>
                                                                                                                                                                  </span>
                                                                                                                                                                  <span class="akn-item" id="sec_17__subsec_5__list_1__item_c" data-eid="sec_17__subsec_5__list_1__item_c">
                                                                                                                                                                    <span class="akn-num">(c)</span>
                                                                                                                                                                    <span class="akn-p">as to whether the applicant has previously had a <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_17__subsec_5__list_1__item_c__term_1" data-eid="sec_17__subsec_5__list_1__item_c__term_1" data-original-title="" title="">working equine</span> removed from his or her care or has a previous criminal conviction or civil judgement against him or her in respect of an <span class="akn-term term-link" data-refersto="#term-animal" id="sec_17__subsec_5__list_1__item_c__term_2" data-eid="sec_17__subsec_5__list_1__item_c__term_2" data-original-title="" title="">animal</span> in his or her care.</span>
                                                                                                                                                                  </span>
                                                                                                                                                                </span>
                                                                                                                                                              </span></section><section class="akn-subsection" id="sec_17__subsec_6" data-eid="sec_17__subsec_6"><span class="akn-num">(6)</span><span class="akn-content">
                                                                                                                                                                  <span class="akn-p">The <span class="akn-term term-link" data-refersto="#term-Council" id="sec_17__subsec_6__term_1" data-eid="sec_17__subsec_6__term_1" data-original-title="" title="">Council</span> may refuse an application in terms of subsection (1) or approve it subject to any conditions aimed at reducing the risk of nuisance in a <span class="akn-term term-link" data-refersto="#term-public_place" id="sec_17__subsec_6__term_2" data-eid="sec_17__subsec_6__term_2" data-original-title="" title="">public place</span> occurring, continuing or recurring or to reduce such risk to a level acceptable to the <span class="akn-term term-link" data-refersto="#term-Council" id="sec_17__subsec_6__term_3" data-eid="sec_17__subsec_6__term_3" data-original-title="" title="">Council</span>.</span>
                                                                                                                                                                </span></section><section class="akn-subsection" id="sec_17__subsec_7" data-eid="sec_17__subsec_7"><span class="akn-num">(7)</span><span class="akn-content">
                                                                                                                                                                    <span class="akn-p">A <span class="akn-term term-link" data-refersto="#term-person" id="sec_17__subsec_7__term_1" data-eid="sec_17__subsec_7__term_1" data-original-title="" title="">person</span> who has applied for a <span class="akn-term term-link" data-refersto="#term-permit" id="sec_17__subsec_7__term_2" data-eid="sec_17__subsec_7__term_2" data-original-title="" title="">permit</span> in terms of subsection (1) may not work a <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_17__subsec_7__term_3" data-eid="sec_17__subsec_7__term_3" data-original-title="" title="">working equine</span> pending the outcome of such application, in the absence of a <span class="akn-term term-link" data-refersto="#term-permit" id="sec_17__subsec_7__term_4" data-eid="sec_17__subsec_7__term_4" data-original-title="" title="">permit</span>.</span>
                                                                                                                                                                  </span></section><section class="akn-subsection" id="sec_17__subsec_8" data-eid="sec_17__subsec_8"><span class="akn-num">(8)</span><span class="akn-content">
                                                                                                                                                                      <span class="akn-p">In respect of any application approved in terms of subsection (6), an <span class="akn-term term-link" data-refersto="#term-authorised_official" id="sec_17__subsec_8__term_1" data-eid="sec_17__subsec_8__term_1" data-original-title="" title="">authorised official</span> must issue a <span class="akn-term term-link" data-refersto="#term-permit" id="sec_17__subsec_8__term_2" data-eid="sec_17__subsec_8__term_2" data-original-title="" title="">permit</span> on a prescribed form specifying every condition imposed by the <span class="akn-term term-link" data-refersto="#term-Council" id="sec_17__subsec_8__term_3" data-eid="sec_17__subsec_8__term_3" data-original-title="" title="">Council</span>.</span>
                                                                                                                                                                    </span></section><section class="akn-subsection" id="sec_17__subsec_9" data-eid="sec_17__subsec_9"><span class="akn-num">(9)</span><span class="akn-content">
                                                                                                                                                                        <span class="akn-p">A <span class="akn-term term-link" data-refersto="#term-permit" id="sec_17__subsec_9__term_1" data-eid="sec_17__subsec_9__term_1" data-original-title="" title="">permit</span> is not transferable from one <span class="akn-term term-link" data-refersto="#term-owner" id="sec_17__subsec_9__term_2" data-eid="sec_17__subsec_9__term_2" data-original-title="" title="">owner</span> to another.</span>
                                                                                                                                                                      </span></section></section><section class="akn-section" id="sec_18" data-eid="sec_18"><h3>18. Amendment, suspension and cancellation of permits</h3>
                                                                                                                                                                        <span class="akn-hcontainer" id="sec_18__hcontainer_1" data-eid="sec_18__hcontainer_1" data-name="hcontainer">
                                                                                                                                                                          <span class="akn-content">
                                                                                                                                                                            <span class="akn-blockList" id="sec_18__hcontainer_1__list_1" data-eid="sec_18__hcontainer_1__list_1">
                                                                                                                                                                              <span class="akn-listIntroduction">The council may, after consideration of a report and recommendation of an <span class="akn-term term-link" data-refersto="#term-authorised_official" id="sec_18__hcontainer_1__list_1__term_1" data-eid="sec_18__hcontainer_1__list_1__term_1" data-original-title="" title="">authorised official</span> or veterinary surgeon, by written notice to the holder of a <span class="akn-term term-link" data-refersto="#term-permit" id="sec_18__hcontainer_1__list_1__term_2" data-eid="sec_18__hcontainer_1__list_1__term_2" data-original-title="" title="">permit</span> contemplated in section 17 –</span>
                                                                                                                                                                              <span class="akn-item" id="sec_18__hcontainer_1__list_1__item_a" data-eid="sec_18__hcontainer_1__list_1__item_a">
                                                                                                                                                                                <span class="akn-num">(a)</span>
                                                                                                                                                                                <span class="akn-blockList" id="sec_18__hcontainer_1__list_1__item_a__list_1" data-eid="sec_18__hcontainer_1__list_1__item_a__list_1">
                                                                                                                                                                                  <span class="akn-listIntroduction">amend, suspend or cancel that <span class="akn-term term-link" data-refersto="#term-permit" id="sec_18__hcontainer_1__list_1__item_a__list_1__term_1" data-eid="sec_18__hcontainer_1__list_1__item_a__list_1__term_1" data-original-title="" title="">permit</span> if it is satisfied that failure to do so would result in-</span>
                                                                                                                                                                                  <span class="akn-item" id="sec_18__hcontainer_1__list_1__item_a__list_1__item_i" data-eid="sec_18__hcontainer_1__list_1__item_a__list_1__item_i">
                                                                                                                                                                                    <span class="akn-num">(i)</span>
                                                                                                                                                                                    <span class="akn-p">the creation or continuation of a nuisance in a <span class="akn-term term-link" data-refersto="#term-public_place" id="sec_18__hcontainer_1__list_1__item_a__list_1__item_i__term_1" data-eid="sec_18__hcontainer_1__list_1__item_a__list_1__item_i__term_1" data-original-title="" title="">public place</span>; or</span>
                                                                                                                                                                                  </span>
                                                                                                                                                                                  <span class="akn-item" id="sec_18__hcontainer_1__list_1__item_a__list_1__item_ii" data-eid="sec_18__hcontainer_1__list_1__item_a__list_1__item_ii">
                                                                                                                                                                                    <span class="akn-num">(ii)</span>
                                                                                                                                                                                    <span class="akn-p">a continued contravention of any provision of section 19</span>
                                                                                                                                                                                  </span>
                                                                                                                                                                                </span>
                                                                                                                                                                              </span>
                                                                                                                                                                              <span class="akn-item" id="sec_18__hcontainer_1__list_1__item_b" data-eid="sec_18__hcontainer_1__list_1__item_b">
                                                                                                                                                                                <span class="akn-num">(b)</span>
                                                                                                                                                                                <span class="akn-p">with immediate effect amend, suspend or cancel that <span class="akn-term term-link" data-refersto="#term-permit" id="sec_18__hcontainer_1__list_1__item_b__term_1" data-eid="sec_18__hcontainer_1__list_1__item_b__term_1" data-original-title="" title="">permit</span> if such official is of the view that it is urgently necessary to do so to eliminate or reduce a significant risk to the public posed by a nuisance in a <span class="akn-term term-link" data-refersto="#term-public_place" id="sec_18__hcontainer_1__list_1__item_b__term_2" data-eid="sec_18__hcontainer_1__list_1__item_b__term_2" data-original-title="" title="">public place</span>.</span>
                                                                                                                                                                              </span>
                                                                                                                                                                            </span>
                                                                                                                                                                          </span>
                                                                                                                                                                        </span></section><section class="akn-section" id="sec_19" data-eid="sec_19"><h3>19. Control of working equines</h3>
                                                                                                                                                                          <span class="akn-hcontainer" id="sec_19__hcontainer_1" data-eid="sec_19__hcontainer_1" data-name="hcontainer">
                                                                                                                                                                            <span class="akn-content">
                                                                                                                                                                              <span class="akn-blockList" id="sec_19__hcontainer_1__list_1" data-eid="sec_19__hcontainer_1__list_1">
                                                                                                                                                                                <span class="akn-listIntroduction">No <span class="akn-term term-link" data-refersto="#term-person" id="sec_19__hcontainer_1__list_1__term_1" data-eid="sec_19__hcontainer_1__list_1__term_1" data-original-title="" title="">person</span> putting to work a <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_19__hcontainer_1__list_1__term_2" data-eid="sec_19__hcontainer_1__list_1__term_2" data-original-title="" title="">working equine</span> shall-</span>
                                                                                                                                                                                <span class="akn-item" id="sec_19__hcontainer_1__list_1__item_a" data-eid="sec_19__hcontainer_1__list_1__item_a">
                                                                                                                                                                                  <span class="akn-num">(a)</span>
                                                                                                                                                                                  <span class="akn-p"><span class="akn-term term-link" data-refersto="#term-permit" id="sec_19__hcontainer_1__list_1__item_a__term_1" data-eid="sec_19__hcontainer_1__list_1__item_a__term_1" data-original-title="" title="">permit</span> the <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_19__hcontainer_1__list_1__item_a__term_2" data-eid="sec_19__hcontainer_1__list_1__item_a__term_2" data-original-title="" title="">working equine</span> to be in any <span class="akn-term term-link" data-refersto="#term-public_place" id="sec_19__hcontainer_1__list_1__item_a__term_3" data-eid="sec_19__hcontainer_1__list_1__item_a__term_3" data-original-title="" title="">public place</span> whilst being incapable of pulling an <span class="akn-term term-link" data-refersto="#term-animal_drawn_vehicle" id="sec_19__hcontainer_1__list_1__item_a__term_4" data-eid="sec_19__hcontainer_1__list_1__item_a__term_4" data-original-title="" title="">animal drawn vehicle</span>;</span>
                                                                                                                                                                                </span>
                                                                                                                                                                                <span class="akn-item" id="sec_19__hcontainer_1__list_1__item_b" data-eid="sec_19__hcontainer_1__list_1__item_b">
                                                                                                                                                                                  <span class="akn-num">(b)</span>
                                                                                                                                                                                  <span class="akn-p"><span class="akn-term term-link" data-refersto="#term-permit" id="sec_19__hcontainer_1__list_1__item_b__term_1" data-eid="sec_19__hcontainer_1__list_1__item_b__term_1" data-original-title="" title="">permit</span> the <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_19__hcontainer_1__list_1__item_b__term_2" data-eid="sec_19__hcontainer_1__list_1__item_b__term_2" data-original-title="" title="">working equine</span> to constitute a hazard to traffic using any public street;</span>
                                                                                                                                                                                </span>
                                                                                                                                                                                <span class="akn-item" id="sec_19__hcontainer_1__list_1__item_c" data-eid="sec_19__hcontainer_1__list_1__item_c">
                                                                                                                                                                                  <span class="akn-num">(c)</span>
                                                                                                                                                                                  <span class="akn-p"><span class="akn-term term-link" data-refersto="#term-permit" id="sec_19__hcontainer_1__list_1__item_c__term_1" data-eid="sec_19__hcontainer_1__list_1__item_c__term_1" data-original-title="" title="">permit</span> the <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_19__hcontainer_1__list_1__item_c__term_2" data-eid="sec_19__hcontainer_1__list_1__item_c__term_2" data-original-title="" title="">working equine</span> to constitute or to his or her knowledge be likely to constitute a source of danger or injury to any <span class="akn-term term-link" data-refersto="#term-person" id="sec_19__hcontainer_1__list_1__item_c__term_3" data-eid="sec_19__hcontainer_1__list_1__item_c__term_3" data-original-title="" title="">person</span> using a public street;</span>
                                                                                                                                                                                </span>
                                                                                                                                                                                <span class="akn-item" id="sec_19__hcontainer_1__list_1__item_d" data-eid="sec_19__hcontainer_1__list_1__item_d">
                                                                                                                                                                                  <span class="akn-num">(d)</span>
                                                                                                                                                                                  <span class="akn-p"><span class="akn-term term-link" data-refersto="#term-permit" id="sec_19__hcontainer_1__list_1__item_d__term_1" data-eid="sec_19__hcontainer_1__list_1__item_d__term_1" data-original-title="" title="">permit</span> the <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_19__hcontainer_1__list_1__item_d__term_2" data-eid="sec_19__hcontainer_1__list_1__item_d__term_2" data-original-title="" title="">working equine</span> to be in any public street or <span class="akn-term term-link" data-refersto="#term-public_place" id="sec_19__hcontainer_1__list_1__item_d__term_3" data-eid="sec_19__hcontainer_1__list_1__item_d__term_3" data-original-title="" title="">public place</span> except when under his or her control;</span>
                                                                                                                                                                                </span>
                                                                                                                                                                                <span class="akn-item" id="sec_19__hcontainer_1__list_1__item_e" data-eid="sec_19__hcontainer_1__list_1__item_e">
                                                                                                                                                                                  <span class="akn-num">(e)</span>
                                                                                                                                                                                  <span class="akn-p">work any <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_19__hcontainer_1__list_1__item_e__term_1" data-eid="sec_19__hcontainer_1__list_1__item_e__term_1" data-original-title="" title="">working equine</span> which does not have on the name, telephone number and address of its <span class="akn-term term-link" data-refersto="#term-owner" id="sec_19__hcontainer_1__list_1__item_e__term_2" data-eid="sec_19__hcontainer_1__list_1__item_e__term_2" data-original-title="" title="">owner</span>;</span>
                                                                                                                                                                                </span>
                                                                                                                                                                                <span class="akn-item" id="sec_19__hcontainer_1__list_1__item_f" data-eid="sec_19__hcontainer_1__list_1__item_f">
                                                                                                                                                                                  <span class="akn-num">(f)</span>
                                                                                                                                                                                  <span class="akn-p"><span class="akn-term term-link" data-refersto="#term-permit" id="sec_19__hcontainer_1__list_1__item_f__term_1" data-eid="sec_19__hcontainer_1__list_1__item_f__term_1" data-original-title="" title="">permit</span> any <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_19__hcontainer_1__list_1__item_f__term_2" data-eid="sec_19__hcontainer_1__list_1__item_f__term_2" data-original-title="" title="">working equine</span> to draw any vehicle, or use any harness which does not comply with the SABS standards and criteria which may be determined by the <span class="akn-term term-link" data-refersto="#term-Council" id="sec_19__hcontainer_1__list_1__item_f__term_3" data-eid="sec_19__hcontainer_1__list_1__item_f__term_3" data-original-title="" title="">Council</span> from time to time.</span>
                                                                                                                                                                                </span>
                                                                                                                                                                              </span>
                                                                                                                                                                            </span>
                                                                                                                                                                          </span></section><section class="akn-section" id="sec_20" data-eid="sec_20"><h3>20. Seizure, impounding and destruction of working equines</h3>
                                                                                                                                                                            <section class="akn-subsection" id="sec_20__subsec_1" data-eid="sec_20__subsec_1"><span class="akn-num">(1)</span><span class="akn-content">
                                                                                                                                                                                <span class="akn-blockList" id="sec_20__subsec_1__list_1" data-eid="sec_20__subsec_1__list_1">
                                                                                                                                                                                  <span class="akn-listIntroduction">An <span class="akn-term term-link" data-refersto="#term-authorised_official" id="sec_20__subsec_1__list_1__term_1" data-eid="sec_20__subsec_1__list_1__term_1" data-original-title="" title="">authorised official</span> may seize and impound at a place appointed by the <span class="akn-term term-link" data-refersto="#term-Council" id="sec_20__subsec_1__list_1__term_2" data-eid="sec_20__subsec_1__list_1__term_2" data-original-title="" title="">Council</span> any <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_20__subsec_1__list_1__term_3" data-eid="sec_20__subsec_1__list_1__term_3" data-original-title="" title="">working equine</span> which-</span>
                                                                                                                                                                                  <span class="akn-item" id="sec_20__subsec_1__list_1__item_a" data-eid="sec_20__subsec_1__list_1__item_a">
                                                                                                                                                                                    <span class="akn-num">(a)</span>
                                                                                                                                                                                    <span class="akn-p">may be destroyed on the advice of a veterinary surgeon or in terms of the provisions of any law;</span>
                                                                                                                                                                                  </span>
                                                                                                                                                                                  <span class="akn-item" id="sec_20__subsec_1__list_1__item_b" data-eid="sec_20__subsec_1__list_1__item_b">
                                                                                                                                                                                    <span class="akn-num">(b)</span>
                                                                                                                                                                                    <span class="akn-p">in his or her opinion is incapable to continue to pull an <span class="akn-term term-link" data-refersto="#term-animal_drawn_vehicle" id="sec_20__subsec_1__list_1__item_b__term_1" data-eid="sec_20__subsec_1__list_1__item_b__term_1" data-original-title="" title="">animal drawn vehicle</span>;</span>
                                                                                                                                                                                  </span>
                                                                                                                                                                                  <span class="akn-item" id="sec_20__subsec_1__list_1__item_c" data-eid="sec_20__subsec_1__list_1__item_c">
                                                                                                                                                                                    <span class="akn-num">(c)</span>
                                                                                                                                                                                    <span class="akn-p">in his or her opinion constitutes a hazard to traffic using any public street;</span>
                                                                                                                                                                                  </span>
                                                                                                                                                                                  <span class="akn-item" id="sec_20__subsec_1__list_1__item_d" data-eid="sec_20__subsec_1__list_1__item_d">
                                                                                                                                                                                    <span class="akn-num">(d)</span>
                                                                                                                                                                                    <span class="akn-p">is at large or apparently without an <span class="akn-term term-link" data-refersto="#term-owner" id="sec_20__subsec_1__list_1__item_d__term_1" data-eid="sec_20__subsec_1__list_1__item_d__term_1" data-original-title="" title="">owner</span>; or</span>
                                                                                                                                                                                  </span>
                                                                                                                                                                                  <span class="akn-item" id="sec_20__subsec_1__list_1__item_e" data-eid="sec_20__subsec_1__list_1__item_e">
                                                                                                                                                                                    <span class="akn-num">(e)</span>
                                                                                                                                                                                    <span class="akn-p">is found in any <span class="akn-term term-link" data-refersto="#term-public_place" id="sec_20__subsec_1__list_1__item_e__term_1" data-eid="sec_20__subsec_1__list_1__item_e__term_1" data-original-title="" title="">public place</span> where such a <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_20__subsec_1__list_1__item_e__term_2" data-eid="sec_20__subsec_1__list_1__item_e__term_2" data-original-title="" title="">working equine</span> is, in the opinion of the <span class="akn-term term-link" data-refersto="#term-authorised_official" id="sec_20__subsec_1__list_1__item_e__term_3" data-eid="sec_20__subsec_1__list_1__item_e__term_3" data-original-title="" title="">authorised official</span>, not under proper control.</span>
                                                                                                                                                                                  </span>
                                                                                                                                                                                </span>
                                                                                                                                                                              </span></section><section class="akn-subsection" id="sec_20__subsec_2" data-eid="sec_20__subsec_2"><span class="akn-num">(2)</span><span class="akn-content">
                                                                                                                                                                                  <span class="akn-p">The <span class="akn-term term-link" data-refersto="#term-Council" id="sec_20__subsec_2__term_1" data-eid="sec_20__subsec_2__term_1" data-original-title="" title="">Council</span> shall keep a record of all working equines seized and impounded in terms of this By-law indicating the species, marks and distinguishing peculiarities (if any) of such working equines, as well as the last date for their release or otherwise, and such records shall be open for inspection by the public at the <span class="akn-term term-link" data-refersto="#term-Council" id="sec_20__subsec_2__term_2" data-eid="sec_20__subsec_2__term_2" data-original-title="" title="">Council</span> Offices during office hours.</span>
                                                                                                                                                                                </span></section><section class="akn-subsection" id="sec_20__subsec_3" data-eid="sec_20__subsec_3"><span class="akn-num">(3)</span><span class="akn-content">
                                                                                                                                                                                    <span class="akn-p">A <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_20__subsec_3__term_1" data-eid="sec_20__subsec_3__term_1" data-original-title="" title="">working equine</span> impounded in terms of subsection (1) shall be released to the <span class="akn-term term-link" data-refersto="#term-owner" id="sec_20__subsec_3__term_2" data-eid="sec_20__subsec_3__term_2" data-original-title="" title="">owner</span> of or <span class="akn-term term-link" data-refersto="#term-person" id="sec_20__subsec_3__term_3" data-eid="sec_20__subsec_3__term_3" data-original-title="" title="">person</span> keeping such <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_20__subsec_3__term_4" data-eid="sec_20__subsec_3__term_4" data-original-title="" title="">working equine</span> upon payment of the fee as fixed by the <span class="akn-term term-link" data-refersto="#term-Council" id="sec_20__subsec_3__term_5" data-eid="sec_20__subsec_3__term_5" data-original-title="" title="">Council</span>.</span>
                                                                                                                                                                                  </span></section><section class="akn-subsection" id="sec_20__subsec_4" data-eid="sec_20__subsec_4"><span class="akn-num">(4)</span><span class="akn-content">
                                                                                                                                                                                      <span class="akn-p">A <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_20__subsec_4__term_1" data-eid="sec_20__subsec_4__term_1" data-original-title="" title="">working equine</span> impounded in terms of subsection (1) may be sold or re-homed after it has been detained for not less than ten days unless it has been claimed and released in terms of subsection (3).</span>
                                                                                                                                                                                    </span></section><section class="akn-subsection" id="sec_20__subsec_5" data-eid="sec_20__subsec_5"><span class="akn-num">(5)</span><span class="akn-content">
                                                                                                                                                                                        <span class="akn-blockList" id="sec_20__subsec_5__list_1" data-eid="sec_20__subsec_5__list_1">
                                                                                                                                                                                          <span class="akn-listIntroduction">If an <span class="akn-term term-link" data-refersto="#term-authorised_official" id="sec_20__subsec_5__list_1__term_1" data-eid="sec_20__subsec_5__list_1__term_1" data-original-title="" title="">authorised official</span> is of the opinion that a <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_20__subsec_5__list_1__term_2" data-eid="sec_20__subsec_5__list_1__term_2" data-original-title="" title="">working equine</span> is a <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_20__subsec_5__list_1__term_3" data-eid="sec_20__subsec_5__list_1__term_3" data-original-title="" title="">working equine</span> contemplated by the provisions of section 19, he or she may-</span>
                                                                                                                                                                                          <span class="akn-item" id="sec_20__subsec_5__list_1__item_a" data-eid="sec_20__subsec_5__list_1__item_a">
                                                                                                                                                                                            <span class="akn-num">(a)</span>
                                                                                                                                                                                            <span class="akn-p">cause a notice to be served on the <span class="akn-term term-link" data-refersto="#term-owner" id="sec_20__subsec_5__list_1__item_a__term_1" data-eid="sec_20__subsec_5__list_1__item_a__term_1" data-original-title="" title="">owner</span> of such <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_20__subsec_5__list_1__item_a__term_2" data-eid="sec_20__subsec_5__list_1__item_a__term_2" data-original-title="" title="">working equine</span> requiring such <span class="akn-term term-link" data-refersto="#term-owner" id="sec_20__subsec_5__list_1__item_a__term_3" data-eid="sec_20__subsec_5__list_1__item_a__term_3" data-original-title="" title="">owner</span> to take such steps as will effectively abate such nuisance and to establish to the satisfaction of the <span class="akn-term term-link" data-refersto="#term-authorised_official" id="sec_20__subsec_5__list_1__item_a__term_4" data-eid="sec_20__subsec_5__list_1__item_a__term_4" data-original-title="" title="">authorised official</span> that such <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_20__subsec_5__list_1__item_a__term_5" data-eid="sec_20__subsec_5__list_1__item_a__term_5" data-original-title="" title="">working equine</span> will be kept under proper control;</span>
                                                                                                                                                                                          </span>
                                                                                                                                                                                          <span class="akn-item" id="sec_20__subsec_5__list_1__item_b" data-eid="sec_20__subsec_5__list_1__item_b">
                                                                                                                                                                                            <span class="akn-num">(b)</span>
                                                                                                                                                                                            <span class="akn-p">impound the <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_20__subsec_5__list_1__item_b__term_1" data-eid="sec_20__subsec_5__list_1__item_b__term_1" data-original-title="" title="">working equine</span> and deal with it in terms of this section, provided that <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_20__subsec_5__list_1__item_b__term_2" data-eid="sec_20__subsec_5__list_1__item_b__term_2" data-original-title="" title="">working equine</span> shall not be released to its <span class="akn-term term-link" data-refersto="#term-owner" id="sec_20__subsec_5__list_1__item_b__term_3" data-eid="sec_20__subsec_5__list_1__item_b__term_3" data-original-title="" title="">owner</span> unless such <span class="akn-term term-link" data-refersto="#term-owner" id="sec_20__subsec_5__list_1__item_b__term_4" data-eid="sec_20__subsec_5__list_1__item_b__term_4" data-original-title="" title="">owner</span>, within the period of ten days contemplated by subsection (4), provides the <span class="akn-term term-link" data-refersto="#term-authorised_official" id="sec_20__subsec_5__list_1__item_b__term_5" data-eid="sec_20__subsec_5__list_1__item_b__term_5" data-original-title="" title="">authorised official</span> with satisfactory proof that such <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_20__subsec_5__list_1__item_b__term_6" data-eid="sec_20__subsec_5__list_1__item_b__term_6" data-original-title="" title="">working equine</span>, if released to him or her, will not cause any further nuisance and will be kept under control.</span>
                                                                                                                                                                                          </span>
                                                                                                                                                                                        </span>
                                                                                                                                                                                      </span></section><section class="akn-subsection" id="sec_20__subsec_6" data-eid="sec_20__subsec_6"><span class="akn-num">(6)</span><span class="akn-content">
                                                                                                                                                                                          <span class="akn-p">The proceeds of any sale shall be used to defray all costs connected with such sale and the impounding of such <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_20__subsec_6__term_1" data-eid="sec_20__subsec_6__term_1" data-original-title="" title="">working equine</span>.</span>
                                                                                                                                                                                        </span></section><section class="akn-subsection" id="sec_20__subsec_7" data-eid="sec_20__subsec_7"><span class="akn-num">(7)</span><span class="akn-content">
                                                                                                                                                                                            <span class="akn-p">Neither the <span class="akn-term term-link" data-refersto="#term-Council" id="sec_20__subsec_7__term_1" data-eid="sec_20__subsec_7__term_1" data-original-title="" title="">Council</span> or the <span class="akn-term term-link" data-refersto="#term-authorised_official" id="sec_20__subsec_7__term_2" data-eid="sec_20__subsec_7__term_2" data-original-title="" title="">authorised official</span> nor the employee of the <span class="akn-term term-link" data-refersto="#term-Council" id="sec_20__subsec_7__term_3" data-eid="sec_20__subsec_7__term_3" data-original-title="" title="">Council</span> shall be liable for or in respect of any injury or disease contracted by or damage caused to any <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_20__subsec_7__term_4" data-eid="sec_20__subsec_7__term_4" data-original-title="" title="">working equine</span> as result of or during its seizure, impounding, detention, sale or destruction in terms of the By-law</span>
                                                                                                                                                                                          </span></section></section><section class="akn-section" id="sec_21" data-eid="sec_21"><h3>21. The rescue of impounded working equines prohibited</h3>
                                                                                                                                                                                            <span class="akn-hcontainer" id="sec_21__hcontainer_1" data-eid="sec_21__hcontainer_1" data-name="hcontainer">
                                                                                                                                                                                              <span class="akn-content">
                                                                                                                                                                                                <span class="akn-p">No <span class="akn-term term-link" data-refersto="#term-person" id="sec_21__hcontainer_1__term_1" data-eid="sec_21__hcontainer_1__term_1" data-original-title="" title="">person</span> shall, by threats of violence or otherwise, rescue or attempt to rescue from the <span class="akn-term term-link" data-refersto="#term-person" id="sec_21__hcontainer_1__term_2" data-eid="sec_21__hcontainer_1__term_2" data-original-title="" title="">person</span> or persons in charge thereof any <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_21__hcontainer_1__term_3" data-eid="sec_21__hcontainer_1__term_3" data-original-title="" title="">working equine</span> being lawfully brought to the <span class="akn-term term-link" data-refersto="#term-pound" id="sec_21__hcontainer_1__term_4" data-eid="sec_21__hcontainer_1__term_4" data-original-title="" title="">pound</span>, or shall rescue or attempt to rescue any <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_21__hcontainer_1__term_5" data-eid="sec_21__hcontainer_1__term_5" data-original-title="" title="">working equine</span> after such <span class="akn-term term-link" data-refersto="#term-working_equine" id="sec_21__hcontainer_1__term_6" data-eid="sec_21__hcontainer_1__term_6" data-original-title="" title="">working equine</span> has been lawfully impounded by an <span class="akn-term term-link" data-refersto="#term-authorised_official" id="sec_21__hcontainer_1__term_7" data-eid="sec_21__hcontainer_1__term_7" data-original-title="" title="">authorised official</span>.</span>
                                                                                                                                                                                              </span>
                                                                                                                                                                                            </span></section></section>
</template>

<script>
export default {
  name: 'Chapter4'
}
</script>